// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbszyDMpyv0vLKCmjRA3a6jurJAqsbc-0',
    appId: '1:326312334815:web:2de8f23132b3c63347206a',
    messagingSenderId: '326312334815',
    projectId: 'my-task-manage',
    authDomain: 'my-task-manage.firebaseapp.com',
    storageBucket: 'my-task-manage.appspot.com',
    measurementId: 'G-8S9M62Q7Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreQZSUWFg3-9jg_vYgD11_71Cksnszbc',
    appId: '1:326312334815:android:d0cd7ec852eaa6f647206a',
    messagingSenderId: '326312334815',
    projectId: 'my-task-manage',
    storageBucket: 'my-task-manage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZ19kek6KAGNuP3A2u_E3ZFwnWq9_0Tc',
    appId: '1:326312334815:ios:ddcb356c4bf01ca947206a',
    messagingSenderId: '326312334815',
    projectId: 'my-task-manage',
    storageBucket: 'my-task-manage.appspot.com',
    iosClientId: '326312334815-d6u3r99b2nv9ndehbljgrgdap5srq508.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZ19kek6KAGNuP3A2u_E3ZFwnWq9_0Tc',
    appId: '1:326312334815:ios:ddcb356c4bf01ca947206a',
    messagingSenderId: '326312334815',
    projectId: 'my-task-manage',
    storageBucket: 'my-task-manage.appspot.com',
    iosClientId: '326312334815-d6u3r99b2nv9ndehbljgrgdap5srq508.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManage',
  );
}
